### ISSUE TITLE
Small Ships and Cachalot Whales

### ISSUE THREAD

**Issue by RainbowSaber** [CrimsonCrips/AlexsMobsInteraction#5]
Cachalot Whales relentlessly and agressively hunt down any player riding a ship from the mod [SmallShips](https://www.curseforge.com/minecraft/mc-mods/small-ships). These ships usually have a large hp pool, can be repaired, have an inventory and are generally a larger investment. As of now (Forge, latest 1.20.1 Version of AlexsMobs), the whales will always oneshot the ships, probably due to them inheriting traits of vanilla boats. This doesn't feel great, since the boats can't outmaneuver/outrun the whales and you sometimes just lose your ship alongside with chests of items, just because you got unlucky.

Could this be fixed on your end? Can you add a bandaid solution of a blacklist for entities the whale shouldnt aggressively attack?

**Comment by CrimsonCrips** [comment]
Hi

i have done some testing and the Cachalot Whale doesnt seem to be hunting your boat, what most likely happened is that the boats from SmallShips hit the Cachalot Whale which has a code to follow, but not attack players that are riding in one, but since the SmallShips deal damage to any that it hits it may have hit the cachalot whale and therefor attacked the boat
