### ISSUE TITLE
[FEATURE] Make Patchouli optional

### ISSUE THREAD

**Issue by Redls07** [CrimsonCrips/AlexsMobsInteraction#50]
You said Patchouli is already optional, but it's not. I also don't understand why you closed the conversation on the last suggestion, so I had to create a new one.

**Comment by CrimsonCrips** [comment]
While i understand your reasons for having patchouli only be optional like with mods like betterend
I am not interested in making it a optional type dependancy as it is really integral for AMI 

Because unlike mods that use patchouli like content mods where you can find out for yourself what their functions is without a wiki most of the time, AMI is a additions mod that cannot be explored easily unlike with mods like BetterEnd, Botania, etc. because it is more harder to figure out whats new and whats changed for AMI 

whether you agree with this or not, I am maintaining my position.

**Comment by Redls07** [comment]
Okay, now I understand the reason
